// AUTO-GENERATED by scripts/build-dementia-model.mts — do not hand-edit.
// Regenerate: node scripts/build-dementia-model.mts
//
// A logistic regression trained on SYNTHETIC data — class-conditional
// feature distributions set from the direction/rough magnitude reported in
// dementia-speech research literature, not from real diagnosed recordings
// (no such dataset is freely fetchable; see the comment at the top of
// build-dementia-model.mts for sources and the exact caveat). This is an
// unvalidated screening heuristic for a hackathon demo, not a clinically
// validated diagnostic model — see DementiaRiskCard for the disclosure
// shown alongside every score it produces.
//
// Generated 2026-08-16T04:05:44.744Z from 8000 synthetic samples
// (6400 train / 1600 holdout).
// Holdout accuracy on synthetic data: 84.2%.
// A typical healthy-pattern recording scores: 15.2%.

import type { MetricKey } from "./types";

// Subset of MetricKey this model actually uses — see FEATURES in
// build-dementia-model.mts for why these ten.
export type DementiaFeatureKey = Extract<MetricKey, "wpm" | "avgPauseSec" | "pauseCount" | "longPauseCount" | "silencePercent" | "speechOnsetSec" | "fillerPerMin" | "repeatedWords" | "lexicalDiversity" | "pitchVariation">;

export const DEMENTIA_RISK_META = {
  generatedAt: "2026-08-16T04:05:44.746Z",
  sampleCount: 8000,
  holdoutAccuracy: 0.8419,
  syntheticData: true,
} as const;

export const DEMENTIA_RISK_FEATURES: DementiaFeatureKey[] = [
  "wpm",
  "avgPauseSec",
  "pauseCount",
  "longPauseCount",
  "silencePercent",
  "speechOnsetSec",
  "fillerPerMin",
  "repeatedWords",
  "lexicalDiversity",
  "pitchVariation",
];

// Raw whole-recording counts that dementiaRisk.ts must divide by recording
// duration (minutes) before standardizing — see the FEATURES comment above.
export const DEMENTIA_RISK_PER_MINUTE_KEYS: DementiaFeatureKey[] = [
  "pauseCount",
  "longPauseCount",
  "repeatedWords",
];

export const DEMENTIA_RISK_BIAS = -1.715614;

export const DEMENTIA_RISK_WEIGHTS: Record<DementiaFeatureKey, number> = {
  wpm: -0.518200,
  avgPauseSec: 0.506738,
  pauseCount: 0.412385,
  longPauseCount: 0.544465,
  silencePercent: 0.503821,
  speechOnsetSec: 0.469898,
  fillerPerMin: 0.549657,
  repeatedWords: 0.504632,
  lexicalDiversity: -0.588236,
  pitchVariation: -0.377915,
};

// mean/std computed from the control (non-dementia-pattern) class only, so
// a standardized value of 0 means "typical healthy speaker" — see the
// standardize() comment in build-dementia-model.mts.
export const DEMENTIA_RISK_NORMALIZATION: Record<DementiaFeatureKey, { mean: number; std: number }> = {
  wpm: { mean: 135.1045, std: 30.3559 },
  avgPauseSec: { mean: 0.5081, std: 0.2678 },
  pauseCount: { mean: 8.0216, std: 4.2920 },
  longPauseCount: { mean: 1.2390, std: 1.1935 },
  silencePercent: { mean: 15.1072, std: 8.7057 },
  speechOnsetSec: { mean: 0.8478, std: 0.5635 },
  fillerPerMin: { mean: 3.2374, std: 2.5885 },
  repeatedWords: { mean: 0.7418, std: 0.8215 },
  lexicalDiversity: { mean: 0.7480, std: 0.1106 },
  pitchVariation: { mean: 24.9275, std: 10.9402 },
};
