// AUTO-GENERATED by scripts/build-reference-stats.mts — do not hand-edit.
// Regenerate: node scripts/build-reference-stats.mts
//
// Source: LibriSpeech validation-clean split (Panayotov et al., 2015),
// fetched via the Hugging Face datasets-server API for
// openslr/librispeech_asr. LibriSpeech compiles public-domain LibriVox
// audiobook narration; dataset license CC BY 4.0. https://www.openslr.org/12
//
// This is short, scripted, single-sentence, studio-quality READ narration —
// not spontaneous multi-minute conversation like a Sona recording. Only
// metrics that stay meaningful across that style gap are included here.
// See src/lib/population.ts for why the rest of RecordingMetrics is
// deliberately excluded from the population comparison.
//
// Generated 2026-08-15 from 200 clips
// across 40 distinct speakers.

import { MetricKey } from "./types";

export type PopulationMetricKey = Extract<MetricKey, "wpm" | "pitchVariation" | "vocalEnergyVariation">;

export interface MetricPercentiles {
  p5: number;
  p10: number;
  p25: number;
  p50: number;
  p75: number;
  p90: number;
  p95: number;
}

export const REFERENCE_META = {
  corpus: "LibriSpeech validation-clean",
  license: "CC BY 4.0",
  sourceUrl: "https://www.openslr.org/12",
  style: "scripted, single-sentence, studio-quality audiobook narration",
  clipCount: 200,
  speakerCount: 40,
  generatedAt: "2026-08-15T20:00:42.080Z",
} as const;

export const REFERENCE_STATS: Record<PopulationMetricKey, MetricPercentiles> = {
  wpm: { p5: 95.847, p10: 117.318, p25: 143.713, p50: 163.543, p75: 181.389, p90: 208.044, p95: 215.873 },
  pitchVariation: { p5: 13.359, p10: 16.039, p25: 20.157, p50: 25.247, p75: 35.304, p90: 46.097, p95: 60.192 },
  vocalEnergyVariation: { p5: 44.072, p10: 46.484, p25: 51.223, p50: 57.814, p75: 66.202, p90: 73.780, p95: 79.229 },
};
